### ISSUE TITLE
[팀원 모집] 같이 팀원하실 1분을 모집합니다.

### ISSUE THREAD

**Issue by ysy970923** [swsnu/osspr2021#20]
안녕하세요. 전기정보공학부 유상윤입니다.
현재 저희 팀은 저와 전기정보공학부 허상혁으로 이루어져있고, 추가로 1분을 더 모집하고자 합니다.
혹시 희망해주시는 분은 ysy970923@snu.ac.kr로 메일 주시거나 xxx-xxxx-xxxx로 연락주시면 감사하겠습니다.
감사합니다!

**Comment by jaywonchung** [comment]
This is a public repo, and you might not want to disclose your phone number here. I redacted your phone number. Feel free to re-edit the post if you still believe that you should open your phone number.

**Comment by ysy970923** [comment]
팀원 모집 완료했습니다. 감사합니다.
